# SQL Validation Rules
# This file defines validation rules for SQL deployments

type_guards:
  create:
    enabled: true
    description: "Validation rules for CREATE statements"
    disallowed_patterns:
      - pattern: '\b(n?varchar|varbinary)\s*\(\s*max\s*\)'
        name: "MAX data types"
        message: "VARCHAR(MAX), NVARCHAR(MAX), and VARBINARY(MAX) are not allowed in CREATE statements"
        severity: error
        reason: "MAX types can cause performance issues and complicate indexing"
        examples:
          bad: "full_name VARCHAR(MAX)"
          good: "full_name NVARCHAR(500)"
      
      - pattern: '\b(text|ntext|image)\b'
        name: "Legacy data types"
        message: "TEXT, NTEXT, and IMAGE types are deprecated"
        severity: error
        reason: "These types are deprecated in modern SQL Server versions"
        examples:
          bad: "description TEXT"
          good: "description NVARCHAR(4000)"
  
  alter:
    enabled: true
    description: "Validation rules for ALTER statements"
    disallowed_patterns:
      - pattern: '\b(n?varchar|varbinary)\s*\(\s*max\s*\)'
        name: "MAX data types"
        message: "Cannot ALTER columns to VARCHAR(MAX), NVARCHAR(MAX), or VARBINARY(MAX)"
        severity: error
        examples:
          bad: "ALTER COLUMN description VARCHAR(MAX)"
          good: "ALTER COLUMN description NVARCHAR(4000)"
      
      - pattern: '\b(text|ntext|image)\b'
        name: "Legacy data types"
        message: "Cannot ALTER columns to deprecated TEXT, NTEXT, or IMAGE types"
        severity: error
  
  drop:
    enabled: false
    description: "DROP statements are controlled by allowlist only"

naming_conventions:
  enabled: false  # Can be enabled later
  tables:
    pattern: '^[a-z][a-z0-9_]*$'
    message: "Table names should be lowercase with underscores"
    examples:
      bad: "UserTable, user-table"
      good: "user_table, users"
  
  columns:
    pattern: '^[A-Z][a-zA-Z0-9]*$'
    message: "Column names should be PascalCase"
    examples:
      bad: "user_name, USERNAME"
      good: "UserName, FirstName"

# Additional validation rules (for future expansion)
performance_checks:
  enabled: false
  rules:
    - name: "Missing indexes on foreign keys"
      severity: warning
    - name: "SELECT * usage"
      severity: warning

security_checks:
  enabled: false
  rules:
    - name: "Dynamic SQL usage"
      severity: warning
    - name: "Missing WHERE clause in UPDATE/DELETE"
      severity: error