IF OBJECT_ID('dbo.CI_TEST', 'U') IS NOT NULL
  DROP TABLE dbo.CI_TEST;
GO

CREATE TABLE dbo.CI_TEST (
  id INT NOT NULL PRIMARY KEY,
  name VARCHAR(100) NULL,
  created_at DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
