name: Probe STAGING SQL Server

on:
  workflow_dispatch: {}   # bisa dijalankan manual dari tab Actions

jobs:
  probe:
    # kalau pakai self-hosted runner internal, ganti jadi: runs-on: self-hosted
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Install tools (sqlcmd + netcat)
        run: |
          sudo su -c 'curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -'
          sudo add-apt-repository "$(curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list)"
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 dnsutils netcat-openbsd
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Show target (masked) + DNS resolve
        env:
          H: ${{ secrets.STG_DB_HOST }}
          P: ${{ secrets.STG_DB_PORT }}
          N: ${{ secrets.STG_DB_NAME }}
        run: |
          echo "Target port: $P"
          echo "Resolving host…"
          getent hosts "$H" || echo "DNS: unable to resolve $H"

      - name: TCP port check (nc)
        env:
          H: ${{ secrets.STG_DB_HOST }}
          P: ${{ secrets.STG_DB_PORT }}
        run: |
          echo "Checking TCP ${H}:${P}…"
          nc -vz -w5 "$H" "$P" && echo "TCP OK" || (echo "TCP FAILED" && exit 1)

      - name: Try sqlcmd login (SELECT 1)
        env:
          H: ${{ secrets.STG_DB_HOST }}
          P: ${{ secrets.STG_DB_PORT }}
          D: ${{ secrets.STG_DB_NAME }}
          U: ${{ secrets.STG_DB_USER }}
          W: ${{ secrets.STG_DB_PASSWORD }}
          # sqlcmd v18 default ENCRYPT=on. Keep it on; trust server cert to ease self-signed.
          SQLCMDENCRYPT: "true"
          SQLCMDTRUSTSERVERCERT: "true"
        run: |
          /opt/mssql-tools18/bin/sqlcmd \
            -S "${H},${P}" \
            -d "${D}" \
            -U "${U}" \
            -P "${W}" \
            -l 10 -b -C \
            -Q "SET NOCOUNT ON; SELECT 1 AS ok, DB_NAME() AS db, SYSTEM_USER AS login;"
